USE [EUC]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STAT](
	[StatId] [int] IDENTITY(1,1) NOT NULL,
	[Kod] [nvarchar](max) NOT NULL,
	[Nazev] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_STAT] PRIMARY KEY CLUSTERED 
(
	[StatId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


CREATE TABLE [dbo].[OSOBA](
	[OsobaId] [int] IDENTITY(1,1) NOT NULL,
	[Jmeno] [nvarchar](max) NOT NULL,
	[Prijmeni] [nvarchar](max) NOT NULL,
	[RC] [nvarchar](max) NOT NULL,
	[MaRc] [bit] NOT NULL,
	[DatNarozeni] [datetime2](7) NULL,
	[Pohlavi] [int] NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[SouhlasSGDPR] [bit] NOT NULL,
	[StatId] [int] NULL,
 CONSTRAINT [PK_OSOBA] PRIMARY KEY CLUSTERED 
(
	[OsobaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


